import { Language } from './types';

export const MAX_ENERGY = 10;
export const ENERGY_RECHARGE_TIME = 60000; // 1 min

export const CONFIG = {
  TELEGRAM_URL: 'https://t.me/your_channel', 
  KOFI_URL: 'https://ko-fi.com/mishkastudios',
  VERSION: '1.4.0',
  DEVELOPER_NAME: 'Mishka Studios'
};

export const TRANSLATIONS = {
  en: {
    title: "NOIR",
    subtitle: "Dark City Detective",
    newCase: "NEW CASE",
    activeCase: "Active Case",
    incidentReport: "Incident Report",
    evidence: "Evidence Found",
    suspects: "Persons of Interest",
    interrogate: "Interrogate",
    solve: "SOLVE CASE",
    back: "Back",
    typing: "Thinking...",
    questionsRemaining: "Questions Remaining",
    askQuestion: "Ask a tough question...",
    outOfEnergy: "Out of energy (Take a Break)",
    whoIsKiller: "Who is the killer?",
    wait: "Wait, I need to check the file again",
    caseClosed: "CASE CLOSED",
    caseCold: "CASE COLD",
    backToOffice: "BACK TO OFFICE",
    restockEnergy: "Take a break (+10 Energy)",
    loading: "SEARCHING CASE FILES...",
    connecting: "Accessing Police Archives",
    liveDb: "ENCRYPTED CONNECTION",
    greeting: (name: string) => `*${name} looks at you with guarded eyes* "What do you want, Detective?"`,
    motive: "Motive",
    successMsg: (name: string) => `Excellent work, detective. ${name} has been taken into custody.`,
    failMsg: (killerName: string) => `You accused the wrong person. The real killer was ${killerName}. The trail has gone cold.`,
    introQuote: "The city is full of shadows. My job? Find the light. One case at a time.",
    shop: "Inventory",
    support: "Support",
    buyCoffee: "Coffee Break",
    price: "FREE",
    joinCommunity: "Join Telegram",
    xp: "Detective Rank",
    level: "Level",
    donate: "Support via Ko-fi"
  },
  ru: {
    title: "NOIR",
    subtitle: "Детектив Темного Города",
    newCase: "НОВОЕ ДЕЛО",
    activeCase: "Активное дело",
    incidentReport: "Отчет об инциденте",
    evidence: "Найденные улики",
    suspects: "Подозреваемые",
    interrogate: "Допросить",
    solve: "РАСКРЫТЬ ДЕЛО",
    back: "Назад",
    typing: "Задумался...",
    questionsRemaining: "Осталось вопросов",
    askQuestion: "Задайте вопрос...",
    outOfEnergy: "Нужен перерыв",
    whoIsKiller: "Кто убийца?",
    wait: "Подождите, нужно проверить досье",
    caseClosed: "ДЕЛО ЗАКРЫТО",
    caseCold: "ДЕЛО ВИСЯК",
    backToOffice: "В ОФИС",
    restockEnergy: "Сделать перерыв (+10 Энергии)",
    loading: "ПОИСК В АРХИВАХ...",
    connecting: "Доступ к полицейской базе данных",
    liveDb: "ЗАШИФРОВАННЫЙ КАНАЛ",
    greeting: (name: string) => `*${name} смотрит на вас с опаской* "Что вам нужно, детектив?"`,
    motive: "Мотив",
    successMsg: (name: string) => `Отличная работа, детектив. ${name} взят под стражу.`,
    failMsg: (killerName: string) => `Вы обвинили невиновного. Настоящий убийца — ${killerName}. След простыл.`,
    introQuote: "Этот город полон теней. Моя работа? Найти свет. Одно дело за раз.",
    shop: "Инвентарь",
    support: "Поддержать",
    buyCoffee: "Перерыв на кофе",
    price: "БЕСПЛАТНО",
    joinCommunity: "Наш Telegram",
    xp: "Ранг Детектива",
    level: "Уровень",
    donate: "Поддержать на Ko-fi"
  }
};